name: fluttery
description: Flutter package that helps with prototyping.
version: 0.0.3
author: Matt Carroll
homepage: https://github.com/matthew-carroll/fluttery

environment:
  sdk: '>=2.12.0'

dependencies:
  flutter:
    sdk: flutter
  
  meta: ^1.11.0
  material_color_utilities: ^0.8.0

dev_dependencies:
  test: ^1.25.2